#https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
#https://mkyong.com/spring-boot/spring-boot-yaml-example/
#https://www.baeldung.com/spring-yaml
#https://mkyong.com/spring-boot/spring-boot-profile-based-properties-and-yaml-example/

spring:
  profiles:
    active: "test"
  main:
    banner-mode: console
  mvc:
    view:      prefix: /WEB-INF/views/
      suffix: .jsp
  banner:      location: classpath:banner/banner.txt 
---

spring:  profiles: dev  

---

spring:
  profiles: oper


